In [1]:
import torch

In [2]:
# 检测CUDA
print(torch.cuda.is_available())

True

In [3]:
# 随机生成一个2×2的张量
print(torch.rand(2, 2))

tensor([[0.6258, 0.1645],
        [0.5276, 0.4713]])


In [5]:
# 使用二维列表创建一个2×3的张量
x = torch.tensor([[0, 0, 1], [1, 1, 1], [0, 0, 0]])
print(x)

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])


In [7]:
# 使用索引改变张量的一个元素
x[0][1] = 3
print(x)

tensor([[0, 3, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [12]:
# 生成填充1的张量
one = torch.ones(2, 2)
print(one)

tensor([[1., 1.],
        [1., 1.]])

In [13]:
# 生成填充0的张量
zero = torch.zeros(2, 2)
print(zero)

tensor([[0., 0.],
        [0., 0.]])

In [16]:
# 张量进行标准数学运算
print(one + zero)
print(zero - one)

tensor([[1., 1.],
        [1., 1.]])
tensor([[-1., -1.],
        [-1., -1.]])


In [17]:
# 1×1的张量可以使用item()取出数值
torch.rand(1).item()

0.663260281085968

In [18]:
# 创建CPU中的tensor
cpu_tensor = torch.rand(2)
cpu_tensor.device

device(type='cpu')

In [19]:
# 将CPU中的张量复制到GPU中
gpu_tensor = cpu_tensor.to("cuda")
gpu_tensor.device

device(type='cuda', index=0)

In [20]:
# 找出张量中的最大张量元素
torch.rand(2, 2).max()

tensor(0.7279)

In [22]:
# 找出张量中的最大元素值
torch.rand(2, 2).max().item()

0.9971559047698975

In [23]:
# 生成的是LongTensor
x.type()

'torch.LongTensor'

In [24]:
# 转FloatTensor
float_tensor = x.to(dtype=torch.float32)
float_tensor.type()

'torch.FloatTensor'

In [25]:
float_tensor

tensor([[0., 3., 1.],
        [1., 1., 1.],
        [0., 0., 0.]])

In [27]:
# 求张量以2为底的对数
float_tensor.log2()

tensor([[  -inf, 1.5850, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [  -inf,   -inf,   -inf]])

In [28]:
# 节约内存
random_tensor = torch.rand(2, 2)
random_tensor.log2_()

tensor([[-0.0627, -1.4152],
        [-0.8316, -2.4452]])

In [29]:
# view()可以完成张量变形
flat_tensor = torch.rand(784)
viewed_tensor = flat_tensor.view(1, 28, 28)
print(viewed_tensor.shape)

torch.Size([1, 28, 28])


In [30]:
# reshape()也可以完成张量变形 更为推荐使用
reshaped_tensor = flat_tensor.reshape(1, 28, 28)
print(reshaped_tensor.shape)

torch.Size([1, 28, 28])


In [33]:
# 如果元素个数不同会报错
# flat_tensor.view(1, 25, 25)
# flat_tensor.view(3, 28, 28)

In [34]:
# 重排张量维度
hwc_tensor = torch.rand(640, 480, 3)
chw_tensor = hwc_tensor.permute(2, 0, 1)
print(chw_tensor.shape)

torch.Size([3, 640, 480])
